#!/bin/sh
# This Script (vbox-install) was created by Rüdiger Beck
# It is released under the GPL Version 3
# For Bugs send mail to (jeffbeck-at-web.de)

SOURCE=/media/SCHULE/virtualbox/
MYMACHINE=$HOME/.VirtualBox/Machines/winXP/

# winXP.xml
mkdir -p $MYMACHINE
cp $SOURCE/localadmin/.VirtualBox/Machines/winXP/winXP.xml $MYMACHINE

# Weiter:
# Zeile MachineEntry aus .VirtualBox/VirtualBox.xml ins HOME 
# --> winXP erscheint in VirtualBox

# Zwei Zeilen mit der Harddisk hinzufuegen
# Achtung End Tag HardDisks erhalten



# die Festplatten-Dateien kommen in /virtual
mkdir -p /virtual/vdi


# besser rsync
#cp /media/SCHULE/virtualbox/virtual/virtual/vdi/winXP.vdi /virtual/vdi

mkdir -p /virtual/Machines/winXP/Snapshots

# besser rsync
#cp /media/SCHULE/virtualbox/virtual/virtual/Machines/winXP/Snapshots/\{8c816439-1e6e-430f-9865-db7a2a96206f\}.vdi /virtual/Machines/winXP/Snapshots


# alles lesbar/schreibbar machen
chown -R bz.bz /virtual