#!/bin/sh
# This Script (vbox-pack) was created by Rüdiger Beck
# It is released under the GPL Version 3
# For Bugs send mail to (jeffbeck-at-web.de)

SAVE=/media/SCHULE/virtualbox/
MYMACHINE=$HOME/.VirtualBox/Machines/winXP-2010/

# Verzeichnis VirtualBox-pack-and-go anlegen

# darin VirtualBox-pack-and-go/.VirtualBox speichern


# /virtual nach VirtualBox-pack-and-go speichern


# snaphots nach VirtualBox-pack-and-go speichern
# evtl. reichen die komprimierten und beschreibungsdateien

